export const products = [
    {
        "count": 34,
        "description": "Learn proven patterns, techniques, and tricks to take full advantage of the Node.js platform. Master well-known design principles to create applications that are readable, extensible, and that can grow big",
        "id": "7567ec4b-b10c-48c5-9345-fc73c48a80aa",
        "price": 49.99,
        "title": "Node.js Design Patterns: Design and implement production-grade Node.js applications using proven patterns and techniques",
        "published": "July 29, 2020",
        "edition": 3,
        "publisher": "Paperback",
        "authors": ["Mario Casciaro", "Luciano Mammino"],
        "coverUrl": "https://images-na.ssl-images-amazon.com/images/I/515wgVc7S9L._SX404_BO1,204,203,200_.jpg",
        "rating": 4.4
    },
    {
        "count": 46,
        "description": "Build scalable web applications using Node.js, Express.js, and the latest ECMAScript techniques, along with deploying applications with AWS and Docker with this updated fifth edition",
        "id": "7567ec4b-b10c-48c5-9345-fc73c48a80a0",
        "price": 29.99,
        "title": "Node.js Web Development: Server-side web development",
        "published": "July 31, 2020",
        "edition": 5,
        "publisher": "Paperback",
        "authors": ["David Herron"],
        "coverUrl": "https://images-na.ssl-images-amazon.com/images/I/41e+IedpQXL._SX404_BO1,204,203,200_.jpg",
        "rating": 5
    },
    {
        "count": 47,
        "description": "Explore what React, Node, TypeScript, Webpack, and Docker have to offer individually, and how they all fit together in modern app development.",
        "id": "7567ec4b-b10c-48c5-9345-fc73c48a80a2",
        "price": 24.27,
        "title": "Modern Full-Stack Development: Using TypeScript, React, Node.js, Webpack, and Docker",
        "published": "Mar 30, 2020",
        "edition": 1,
        "publisher": "Paperback",
        "authors": ["Frank Zammetti"],
        "coverUrl": "https://images-na.ssl-images-amazon.com/images/I/41q4NK-yIAL._SX348_BO1,204,203,200_.jpg",
        "rating": 4.6
    },
    {
        "count": 22,
        "description": "JavaScript is the programming language of the web and is used by more software developers today than any other programming language. For nearly 25 years this best seller has been the go-to guide for JavaScript programmers. The seventh edition is fully updated to cover the 2020 version of JavaScript, and new chapters cover classes, modules, iterators, generators, Promises, async/await, and metaprogramming. You’ll find illuminating and engaging example code throughout.",
        "id": "7567ec4b-b10c-48c5-9345-fc73c48a80a1",
        "price": 39.71,
        "title": "JavaScript: The Definitive Guide: Master the World's Most-Used Programming Language",
        "published": "Jun 2, 2020",
        "edition": 7,
        "publisher": "Paperback",
        "authors": ["David Flanagan"],
        "coverUrl": "https://images-na.ssl-images-amazon.com/images/I/51wijnc-Y8L._SX379_BO1,204,203,200_.jpg",
        "rating": 4.7
    },
    {
        "count": 11,
        "description": "Get Programming with Node.js teaches you to write server-side code in JavaScript using Node.js. In 37 fast-paced, fun, and practical lessons, you'll discover how to extend your existing JavaScript skills to write back-end code for your web applications.",
        "id": "7567ec4b-b10c-48c5-9345-fc73c48a80a6",
        "price": 45.28,
        "title": "Get Programming with Node.js",
        "published": "Mar 15, 2019",
        "edition": 1,
        "publisher": "Paperback",
        "authors": ["Jonathan Wexler"],
        "coverUrl": "https://images-na.ssl-images-amazon.com/images/I/41-OvBpNo9L._SX397_BO1,204,203,200_.jpg",
        "rating": 4.5
    },
    {
        "count": 8,
        "description": "In this book, we take you on a fun, hands-on and pragmatic journey to learning Node.js, Express and MongoDB development. You'll start building your first Node.js app within minutes. Every chapter is written in a bite-sized manner and straight to the point as I don’t want to waste your time (and most certainly mine) on the content you don't need. In the end, you will have the skills to create a blog app and deploy it to the Internet.",
        "id": "7567ec4b-b10c-48c5-9345-fc73348a80a1",
        "price": 17.99,
        "title": "Beginning Node.js, Express & MongoDB Development",
        "published": "Jul 10, 2019",
        "edition": 1,
        "publisher": "Paperback",
        "authors": ["Greg Lim"],
        "coverUrl": "https://images-na.ssl-images-amazon.com/images/I/41c5+a3VaXL._SX404_BO1,204,203,200_.jpg",
        "rating": 4.4
    },
    {
        "count": 45,
        "description": "Beginning Node.js is your step-by-step guide to learning all the aspects of creating maintainable Node.js applications. You will see how Node.js is focused on creating high-performing, highly-scalable websites, and how easy it is to get started. Many front-end devs regularly work with HTML, CSS, PHP, even WordPress, but haven't yet got started with Node.js. This book explains everything for you from a beginner level, enabling you to start using Node.js in your projects right away.",
        "id": "7567ec4b-b10c-48c5-9445-fc73c48a80a2",
        "price": 42.61,
        "title": "Beginning Node.js",
        "published": "Nov 25, 2014",
        "edition": 1,
        "publisher": "Paperback",
        "authors": ["Basarat Syed"],
        "coverUrl": "https://images-na.ssl-images-amazon.com/images/I/41c5+a3VaXL._SX404_BO1,204,203,200_.jpg",
        "rating": 3.8
    },
    {
        "count": 3,
        "description": "Build fast, robust, and maintainable modern full-stack web applications using MongoDB, Express, Angular, and Node.js.",
        "id": "7567ec4b-b10c-45c5-9345-fc73c48a80a1",
        "price": 34.99,
        "title": "MongoDB, Express, Angular, and Node.js Fundamentals: Become a MEAN master and rule the world of web applications",
        "published": "Mar 7, 2019",
        "edition": 1,
        "publisher": "Paperback",
        "authors": ["Paul Oluyege"],
        "coverUrl": "https://images-na.ssl-images-amazon.com/images/I/51e6qn4svwL._SX404_BO1,204,203,200_.jpg",
        "rating": 1
    }
]
